// English Translations — Japanese base text → English
// Keys are the Japanese strings displayed as the default language.
// Values are the English equivalents shown when the user selects English.
const englishTranslations = {

    // Chart labels
    '燃料': 'Fuel',
    '機体整備': 'Airframe Maintenance',
    'エンジン・APU整備': 'Engine/APU Maintenance',
    'その他変動費': 'Other Variable Costs',
    '乗組員給与・福利厚生': 'Crew Salary & Benefits',
    '管理': 'Management',

    // G550 section titles
    '内部': 'Interior',
    '外部': 'Exterior',
    'エンジン・APU': 'Engine & APU',

    // ── Aircraft Specs Main Page ─────────────────────────────────────────
    '航空機検索': 'Aircraft Search',
    'お探しの航空機が決まっていますか？以下に入力して直接ページに移動してください': 'Already know what aircraft you are looking for? Please type it below to go directly to the page',
    '仕様データベース': 'Specifications Database',
    '航空機仕様データベース': 'Aircraft Specifications Database',
    '世界をリードする製造業者の航空機の詳細仕様、性能データ、技術情報をご覧ください': 'Explore detailed specifications, performance data, and technical information for aircraft from leading manufacturers worldwide',
    '航空機を検索...': 'Search aircraft...',
    '航空機タイプ別に閲覧': 'Browse by Aircraft Type',
    '航空機タイプを選択して仕様と性能データをご覧ください': 'Select an aircraft type to explore specifications and performance data',
    'ビジネスジェット': 'Business Jet',
    'エグゼクティブ＆プライベート航空': 'Executive & Private Aviation',
    'ターボプロップ機': 'TurboProp Aircraft',
    '効率的な地域輸送': 'Efficient Regional Transport',
    'ピストン機': 'Piston Aircraft',
    '一般航空': 'General Aviation',
    '回転翼機': 'Rotorcraft',
    'ヘリコプター': 'Helicopters',
    'ジェット旅客機': 'Jet Airliner',
    '商用旅客機': 'Commercial Passenger Jets',
    'ピストン回転翼機': 'Piston Rotorcraft',
    '軽量ヘリコプター': 'Light Helicopters',
    'タービン回転翼機': 'Turbine Rotorcraft',
    '大型＆中型ヘリコプター': 'Heavy & Medium Helicopters',
    '提供内容': "What You'll Find",
    'インタラクティブチャート': 'Interactive Charts',
    'インタラクティブなグラフと比較で性能データを視覚化': 'Visualize performance data with interactive graphs and comparisons',
    '詳細仕様': 'Detailed Specifications',
    '寸法、重量、容量を含む包括的な技術データ': 'Comprehensive technical data including dimensions, weights, and capacities',
    '性能指標': 'Performance Metrics',
    '速度、航続距離、上昇限度、燃料消費データ': 'Speed, range, ceiling, and fuel consumption data',
    '高品質画像': 'High-Quality Images',
    '各航空機の詳細写真と図表': 'Detailed photos and diagrams of each aircraft',
    'データベースについて': 'About This Database',
    '当社の包括的な航空機仕様データベースは、航空愛好家、専門家、研究者向けに正確で最新の情報を提供します。各航空機プロファイルには、詳細な技術仕様、性能データ、インタラクティブな視覚化が含まれており、現代および歴史的な航空機の能力と特性を理解するのに役立ちます。': 'Our comprehensive aircraft specifications database provides accurate, up-to-date information for aviation enthusiasts, professionals, and researchers. Each aircraft profile includes detailed technical specifications, performance data, and interactive visualizations to help you understand the capabilities and characteristics of modern and historical aircraft.',

    // ── Business Jets Page ───────────────────────────────────────────────
    'ビジネスジェットについて': 'About Business Jets',
    'ビジネスジェットは、少人数のグループを快適でスタイリッシュに輸送するために設計された航空機です。地域旅行に最適な軽量ジェットから、大陸間飛行が可能な超長距離機まで様々です。ビジネスジェットは、柔軟性、プライバシー、時間の節約、商用航空会社では利用できない小規模空港へのアクセスを提供します。': 'Business jets are aircraft designed for transporting small groups of people in comfort and style. They range from light jets perfect for regional travel to ultra-long-range aircraft capable of intercontinental flights. Business jets offer flexibility, privacy, time savings, and access to smaller airports unavailable to commercial airlines.',
    '以下の航空機サイズカテゴリーから、ミッション要件に最適なビジネスジェットをお探しください。': 'Browse by aircraft size category below to find the perfect business jet for your mission requirements.',

    // Aircraft categories (JS-generated)
    '軽量ビジネスジェット': 'Light Business Jets',
    '中型ビジネスジェット': 'Midsize Business Jets',
    '大型中距離ビジネスジェット': 'Super Midsize Business Jets',
    '大型ビジネスジェット': 'Large Business Jets',
    '超長距離ビジネスジェット': 'Ultra Long-Range Business Jets',
    '近日公開': 'Coming Soon',
    '詳細': 'Details',
    '航続距離': 'Range',
    '最大速度': 'Max Speed',
    '乗客数': 'Passengers',

    // JS-generated aircraft descriptions
    '主翼上エンジン搭載の軽量ジェット': 'Light jet with over-the-wing engines',
    '燃料容量を増大させたHA-420の改良版': 'Improved HA-420 with more fuel capacity',
    '性能向上版のエリート': 'Enhanced Elite with better performance',
    'システムを強化した最新エリート': 'Latest Elite with upgraded systems',
    '短距離移動向けの超軽量ジェット': 'Very light jet for short hops',
    '経済性の高いエントリーレベルCJ': 'Entry-level CJ with good economy',
    'CJ1より航続距離・速度を向上': 'Improved range and speed over CJ1',
    '立入式キャビン付きの人気軽量ジェット': 'Popular light jet with stand-up cabin',
    'CJファミリー最大モデル': 'Largest of the CJ family',
    '優れた性能の中型ジェット': 'Mid-size jet with strong performance',
    '大陸横断旅行向けの広々キャビン': 'Spacious cabin for transcontinental travel',
    '高速スーパー中型ジェット': 'High-speed super mid-size jet',
    'シタシリーズの長距離フラッグシップ': 'Long-range flagship of the Citation line',
    '経済性の高いエントリーレベルガルフストリーム': 'Entry-level Gulfstream with efficiency',
    'クラシックな大型キャビン軽量ビジネスジェット': 'Classic large-cabin light business jet',
    '現代的な効率と航続距離': 'Modern efficiency and range',
    '快適なキャビンを備えたコーポレートジェット': 'Corporate jet with comfortable cabin',
    'G300ベースの長距離版': 'Derived from G300 with longer range',
    '高性能スーパー中型ジェット': 'Highly capable super mid-size jet',
    'バランスの取れた長距離機': 'Well-balanced long-range performer',
    '高度なコックピットを備えた次世代機': 'Next generation with advanced cockpit',
    '卓越した性能とキャビン快適性を誇る超長距離ジェット': 'Ultra-long-range jet with exceptional performance and cabin comfort',
    '高速・長距離フラッグシップ': 'High-speed, long-range flagship',
    'フラッグシップ超長距離機': 'Flagship ultra-long-range aircraft',
    '記録的な能力を持つ航続距離延長版': 'Extended range version with record capability',

    // Category description (JS-generated)
    'HondaJet機（航続距離順）': 'HondaJet aircraft ordered by range.',
    'Cessna機（航続距離順）': 'Cessna aircraft ordered by range.',
    'Gulfstream機（航続距離順）': 'Gulfstream aircraft ordered by range.',

    // ── G550 Aircraft Page ───────────────────────────────────────────────
    'ガルフストリーム G550': 'Gulfstream G550',
    '超長距離ビジネスジェット': 'Ultra Long-Range Business Jet',
    'ガルフストリームG550超長距離ビジネスジェットの詳細仕様、性能分析、コスト内訳、インタラクティブ航続距離マップです。': 'Detailed specifications, performance analysis, cost breakdown, and interactive range mapping for the Gulfstream G550 ultra long-range business jet.',

    // Summary
    '概要': 'Summary',
    'フェリー航続距離': 'Ferry Range',
    '通常巡航速度': 'Normal Cruise Speed',
    '最大乗客数': 'Maximum Passengers',
    'ガルフストリーム G550は2003年から2021年まで製造され、2名の乗組員を必要とし、最大18名の乗客を輸送できます。最大運用高度は15,545 M（51,000 FT）、通常巡航速度は904 KMH（488 KTS）、最大航続距離は12,501 KM（6,750 NM）です。': 'The Gulfstream G550, manufactured from 2003-2021, requires a 2 person crew and can transport up to 18 passengers. The aircraft has a maximum operating altitude of 15,545 M (51,000 FT), a normal cruise speed of 904 KMH (488 KTS), and a 12,501 KM (6,750 NM) maximum range.',

    // Cost
    'コスト分析': 'Cost Analysis',
    '年間飛行時間：': 'Annual Flight Hours:',
    '計画された年間飛行時間を入力してカスタマイズされたコスト予測を確認してください。': 'Enter your planned annual flight hours to see customized cost projections.',
    '通貨：': 'Currency:',
    '為替レートはライブプロバイダーから更新されます。': 'Currency rates update from a live exchange-rate provider.',
    'ライブ燃料価格': 'Live Fuel Price',
    '最新レートを取得中…': 'Fetching latest rate…',
    'レート：': 'Rate:',
    '最終更新：': 'Last updated:',
    'レート更新': 'Refresh Rate',
    '年間総コスト概要': 'Total Annual Cost Summary',
    '年間変動費': 'Annual Variable Cost',
    '年間固定費': 'Annual Fixed Cost',
    '年間総予算': 'Total Annual Budget',
    '月間総予算': 'Total Monthly Budget',
    '時間あたりコスト': 'Cost Per Hour',
    '時間変動費': 'Hourly Variable Cost',
    '燃料': 'Fuel',
    '機体メンテナンス': 'Airframe Maintenance',
    'エンジン/APUメンテナンス': 'Engine & APU Maintenance',
    '変動費その他': 'Miscellaneous Variable',
    '時間変動費合計': 'Total Hourly Variable Costs',
    '年間固定費明細': 'Annual Fixed Cost',
    '乗組員給与＆福利厚生': 'Crew Salary & Benefits',
    '乗組員訓練': 'Crew Training',
    '格納庫': 'Hangar',
    '保険': 'Insurance',
    'その他固定費': 'Miscellaneous Fixed',
    '年間固定費合計': 'Total Annual Fixed Costs',
    '変動費内訳': 'Variable Cost Breakdown',
    '固定費内訳': 'Fixed Cost Breakdown',

    // Performance
    '性能': 'Performance',
    '速度性能': 'Speed Performance',
    '最大速度': 'Maximum Speed',
    '長距離巡航': 'Long-Range Cruise',
    '航続距離能力': 'Range Capabilities',
    '最大航続距離': 'Maximum Range',
    '上昇限度': 'Service Ceiling',
    '上昇率': 'Rate of Climb',
    '重量仕様': 'Weight Specifications',
    '最大離陸重量': 'Max Takeoff Weight',
    '最大着陸重量': 'Max Landing Weight',
    '基本運用重量': 'Basic Operating Weight',
    '燃料消費': 'Fuel Consumption',
    '時間あたり燃料使用量': 'Fuel Usage Per Hour',
    '総燃料容量': 'Total Fuel Capacity',
    '燃料重量': 'Fuel Weight',
    '滑走路距離要件': 'Runway Distance Requirements',
    'メートル': 'Meters',
    'フィート': 'Feet',
    '最短離陸距離': 'Minimum Takeoff Distance',
    '最短着陸距離（PART 91）': 'Minimum Landing Distance (PART 91)',
    '最短着陸距離（PART 135）': 'Minimum Landing Distance (PART 135)',
    '滑走路の測定値は、晴天・乾燥した滑走路を基準とした最短値です。距離は乗客の体重、手荷物の重量、風、滑走路の状態、気温、空港の標高によって変わる場合があります。': 'The runway measurements are the minimum values based on a clear day and dry runway. The distance may change depending on passenger weights, baggage weight, winds, runway conditions, temperature and airport elevation.',
    'インタラクティブ航続距離マップ': 'Interactive Range Map',
    '出発空港を検索：': 'Search Departure Airport:',
    '空港名またはコードで検索（例：東京またはHND）...': 'Search by airport name or code (e.g., Tokyo or HND)...',
    '空港を検索して選択し、その場所からのG550の航続距離を確認': "Search and select an airport to see the G550's range from that location",
    '青いレンジリングは、ガルフストリーム社公表の航続距離です。これは乗客8名＋乗員4名、かつ良好な風・気象条件を前提としています。乗客が増えると最大ペイロードを超えるため、追加搭乗には燃料を減らす必要があります。': 'The blue range ring represents the range published by Gulfstream. This assumes 8 passengers and 4 crew under favorable wind and weather conditions. As passenger count increases beyond the maximum payload, fuel must be reduced to accommodate additional occupants.',
    '最大の19名搭乗時には、重量に対応するため大幅な燃料削減が必要です。赤いレンジリングはその際の平均的な目安ですが、実際の航続距離は天候や風の影響で増減します。': 'At full capacity of 19 passengers, a significant fuel reduction is required to manage the weight. The red range ring provides an average estimate for this configuration; actual range will vary with weather and wind conditions.',
    'フェリー飛行航続距離：6,776 NM（12,548 KM）': 'Ferry Flight Range: 6,776 NM (12,548 KM)',
    '満席時航続距離（18名）：4,200 NM（7,778 KM）': 'Full Seat Range (18 Passengers): 4,200 NM (7,778 KM)',

    // Design
    '設計': 'Design',
    '座席配置': 'Seating Configuration',
    '標準構成': 'Typical Configuration',
    '最小乗組員': 'Minimum Crew',
    '客室乗務員': 'Flight Attendants',
    'キャビン寸法': 'Cabin Dimensions',
    'キャビン容積': 'Cabin Volume',
    'キャビン高さ': 'Cabin Height',
    'キャビン幅': 'Cabin Width',
    'キャビン長さ': 'Cabin Length',
    '荷物＆収納': 'Baggage & Storage',
    '総荷物容量': 'Total Baggage Capacity',
    '内部荷物': 'Internal Baggage',
    '外部荷物': 'External Baggage',
    '外装寸法': 'Exterior Dimensions',
    '全長': 'Overall Length',
    '翼幅': 'Wingspan',
    '高さ': 'Height',
    '翼面積': 'Wing Area',
    'パワープラント': 'Powerplant',
    'エンジン': 'Engines',
    'エンジンモデル': 'Engine Model',
    'エンジンあたり推力': 'Thrust Per Engine',
    '総推力': 'Total Thrust',
    'モデル': 'Model',
    '出力': 'Power Output',

    // ── Aerolab Non-Specs Pages (Japanese → English) ────────────────────
    // Home page
    '少年の頃から憧れた空へ': 'Towards the Skies We Have Always Dreamed Of',
    'エアロラボは、日本の八尾空港に位置する航空関連企業です。弊社は航空機のメンテナンス、修理、\n\t\t\t\t\t整備などのサービスを提供しています。エアロラボの専門技術者は航空機の安全性とパフォーマンスを維持するために、\n\t\t\t\t\t高品質な作業を行っています。また、航空機関連の部品や設備の供給も行っており、顧客のニーズに応じたソリューションを提供しています。\n\t\t\t\t\t私たちは航空産業において重要な役割を果たしており、安全で信頼性の高い航空機の維持に貢献しています。': 'Aerolab is an aviation company located at Yao Airport in Japan. We provide services including aircraft maintenance, repair, and inspection. Our expert technicians perform high-quality work to maintain the safety and performance of aircraft. We also supply aircraft-related parts and equipment, offering solutions tailored to our customers\' needs. We play an important role in the aviation industry and contribute to the safe and reliable maintenance of aircraft.',
    'エアロラボでは航空機の販売や整備をはじめ、通常では調整が難しいとされている航空局との調整も': 'At Aerolab, in addition to aircraft sales and maintenance, we also handle coordination with the Civil Aviation Bureau—',
    '代行いたします。日本最高峰の技術とスタッフが様々なクライアント様のご要望を解決いたします。': 'which is typically difficult to arrange. Our top-class Japanese technicians and staff resolve the diverse needs of our clients.',
    '株式会社エアロラボインターナショナル は、大阪府八尾市にある航空機販売、航空機整備会社です。航空技術の研究開発と航空産業の進化を目指して革新的な技術と優れた専門知識を持つチームが、航空産業のニーズに応えるために努力しています。品質と信頼性にも注力し、最先端のソリューションを提供します。': 'Aerolab International Co., Ltd. is an aircraft sales and maintenance company located in Yao City, Osaka Prefecture. A team with innovative technology and outstanding expertise is working to meet the needs of the aviation industry, with the goal of researching, developing, and evolving aviation technology. We also focus on quality and reliability, providing cutting-edge solutions.',
    'エアロラボグループ各社のウェブサイトは、下のカードよりご覧いただけます。': 'You can view the websites of each Aerolab Group company via the cards below.',

    // Nav items (Japanese text in h2)
    '航空機・ヘリコプター販売': 'Aircraft Sales',
    '航空機整備': 'Maintenance',
    '輸送・サルベージ': 'Transport & Salvage',
    '改造': 'Remodeling',
    '塗装': 'Painting',
    '塗装工程': 'Painting Process',
    '塗装結果': 'Paint Results',
    'その他': 'Other Services',
    '会社概要': 'Our Company',
    '業務実績': 'Achievements',
    'IR情報': 'Investor Relations',
    '採用情報': 'Recruitment',
    '情報セキュリティ基本方針': 'Security Policy',
    'お問い合わせ': 'Contact Us',
    'エアロラボ韓国': 'Aerolab Korea',
    'パイロットショップ': 'Pilot Shop',
    '航空スペック': 'Aircraft Specs',

    // ── Runway chart X-axis ────────────────────────────────────────────────────
    '距離': 'Distance',

    // ── G550 Cost Section ──────────────────────────────────────────────────
    '計算設定': 'Calculation Settings',
    '単位系': 'Unit System',
    'メートル法': 'Metric',
    'ヤード・ポンド法': 'Imperial',

    // ── G550 Disclaimer ─────────────────────────────────────────────────────
    '免責事項': 'Disclaimer',
    '本ページに掲載されている航空機の仕様および性能データ等の情報は、一般的な参考情報として提供されています。これらのデータは、メーカーの公開資料、業界情報、および当社独自の推定に基づいて作成されており、一部には概算値や前提条件が含まれる場合があります。': 'The aircraft specifications, performance data, and related information presented on this page are provided for general informational purposes only. Data is compiled from publicly available manufacturer publications, industry sources, and internal estimates, and may include approximations or assumptions.',
    '航続距離、搭載量、速度などの性能数値は、機体の仕様や状態、気象条件、運用環境などのさまざまな要因によって変動するため、実際の数値は掲載内容と異なる場合があります。': 'Performance figures such as range, payload, and speed are influenced by variables including aircraft configuration, condition, weather, and operational factors. Actual results may vary from the values shown.',
    '本ページに掲載されている画像およびビジュアルは、AI生成または当社により作成されたイメージであり、特定の実機を正確に再現したものではありません。': 'All images and visual representations are AI-generated or created in-house for illustrative purposes only and do not depict any specific aircraft or guarantee accuracy in design or configuration.',
    'また、メーカーの更新、規制の変更、市場動向、地政学的要因などにより、掲載情報が最新でない場合があります。当社は、本情報の正確性、完全性、最新性についていかなる保証も行いません。': 'Information may become outdated due to manufacturer updates, regulatory changes, market conditions, or geopolitical factors. We do not guarantee the accuracy, completeness, or timeliness of the content provided.',
    '本情報は「現状有姿」で提供されるものであり、その利用によって生じたいかなる損害についても、当社は一切の責任を負いません。': 'All information is provided "as is" without warranties of any kind, and we assume no liability for errors, omissions, or outcomes resulting from its use.',
};

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = englishTranslations;
}
