// English Translations — Japanese base text → English
// Keys are the Japanese strings displayed as the default language.
// Values are the English equivalents shown when the user selects English.
const englishTranslations = {

    // ── NAV ───────────────────────────────────────────────────────────────
    '航空機・ヘリコプター販売': 'Aircraft Sales',
    '航空機整備': 'Maintenance',
    '輸送・サルベージ': 'Transport & Salvage',
    '改造': 'Remodeling',
    '塗装': 'Painting',
    'その他': 'Other Services',
    '会社概要': 'Our Company',
    '業務実績': 'Achievements',
    'IR情報': 'Investor Relations',
    '採用情報': 'Recruitment',
    '情報セキュリティ基本方針': 'Security Policy',
    'お問い合わせ': 'Contact Us',
    'エアロラボ韓国': 'Aerolab Korea',
    'パイロットショップ': 'Pilot Shop',
    '航空スペック': 'Aircraft Specs',

    // ── LINKBOX / FOOTER ──────────────────────────────────────────────────
    '航空機販売': 'Aircraft Sales',
    '改造・内装': 'Remodeling & Interior',

    // ── HOME ──────────────────────────────────────────────────────────────
    '少年の頃から憧れた空へ': 'Towards the Skies We Have Always Dreamed Of',
    'エアロラボは、大阪・八尾空港を拠点とする航空関連企業です。航空機の販売・整備・運航を通じ、日本の空の安全と発展を支えています。専門技術者の知見と経験を活かし、機体の状態に応じた最適な対応を実施。高品質なサービスにより、安全性と効率性の両立を追求しております。部品や設備の供給にも対応し、現場のニーズに即した柔軟な支援を展開。法令や基準を遵守しながら、創意工夫により新たな価値を創出いたします。信頼されるパートナーとして、これからも独自の強みを活かし続けていきます。': 'Aerolab is an aviation company based at Yao Airport in Osaka. Through aircraft sales, maintenance, and operations, we support the safety and development of Japan\'s aviation sector. Drawing on the expertise and experience of our specialist technicians, we deliver optimal solutions tailored to each aircraft\'s condition. We pursue both safety and efficiency through high-quality service. We also handle parts and equipment supply, providing flexible on-site support. While complying with all laws and standards, we continue to create new value through innovation. As a trusted partner, we will keep leveraging our unique strengths for years to come.',
    'エアロラボでは、航空機の販売や整備に加え、関係機関との各種調整や手続きにも対応しております。専門性が求められる案件にも的確に取り組み、運用全体を円滑に進めてまいります。日本最高峰の技術力と経験豊富なスタッフが、それぞれのご要望に応じた最適な解決策をご提案いたします。': 'At Aerolab, in addition to aircraft sales and maintenance, we handle various coordination and procedures with relevant authorities. We address even highly specialized matters with precision, ensuring smooth overall operations. Our world-class technical expertise and experienced staff stand ready to propose the optimal solution for each of your needs.',
    '当社では、航空機関連事業における各種実績や取り組みを適切に開示するとともに、企業としての透明性向上に努めています。また、今後の成長を見据えた採用活動にも注力し、多様な人材の参画を推進しています。会社概要、業務実績、採用に関する詳細については、各ページよりご確認ください。': 'We are committed to appropriately disclosing our achievements and initiatives in the aviation industry while enhancing transparency as a company. We also focus on recruiting diverse talent to drive future growth. For details on our company profile, track record, and recruitment, please visit each page.',
    'エアロラボグループ各社のウェブサイトは、下のカードよりご覧いただけます。': 'You can view the websites of each Aerolab Group company via the cards below.',

    // ── SALES ─────────────────────────────────────────────────────────────
    '強み': 'Our Strengths',
    '当社スタッフが海外で買い付け': 'Our Staff Sources Aircraft Overseas',
    '国内外問わずお客様のご要望に応じて様々な国から機体を買い付けることが可能です。ご予算やご希望に応じて独自のネットワークで最高の機体をお探しいたします。さらに、外国で購入した航空機を分解輸送やフェリーフライトをすることも可能です。': 'We are able to source aircraft from various countries both domestically and internationally according to our clients\' requests. Using our unique network, we will find the best aircraft to suit your budget and requirements. We can also arrange disassembly transport or ferry flights for aircraft purchased abroad.',
    '整備から運行手続きを一貫': 'End-to-End from Maintenance to Registration',
    '買い付けた機体をプロの目でチェックし安全性等を再度確認します。国内外問わず様々な場所から日本まで輸送できることも当社の強みです。尚、ご購入いただいた機体の各種手続き（耐空証明取得、RVSM航行の許可取得、RNAV航行の許可取得や、修理改造検査（内装の変更、アビオニクスの変更）なども請け負っております。': 'We professionally inspect all sourced aircraft to re-confirm safety standards. Our ability to transport aircraft from locations worldwide to Japan is one of our key strengths. We also handle all paperwork for purchased aircraft, including airworthiness certification, RVSM authorization, RNAV authorization, and repair/modification inspections such as interior and avionics changes.',
    '販売実績': 'Sales Highlights',
    '2006年式': '2006 Model',
    '2009年式': '2009 Model',
    '2018年式': '2018 Model',
    'お客様のご要望に基づき、ガルフストリーム G550 の導入をサポートいたしました。機体選定から条件交渉まで対応し、ご要望に適合する機体を確保しております。ご購入に際しては、必要な整備・修繕および各種手続きを確実に実施し、長距離・大陸間の国際フライトに対応可能な万全の状態で機体を引き渡しました。その後は、当社パイロットによりアメリカから日本へのフェリーフライトを安全に実施。現在は整備チームが継続的な機体整備を担当し、導入から運航・整備まで一貫した体制で支援しております。': 'We supported the introduction of the Gulfstream G550 based on the client\'s requirements, handling everything from aircraft selection to contract negotiation. Prior to delivery, all necessary maintenance, repairs, and procedures were carried out, and the aircraft was handed over in full readiness for long-range and intercontinental flights. Our pilots then safely conducted the ferry flight from the United States to Japan. The maintenance team now handles ongoing airframe upkeep, providing end-to-end support from acquisition through operations and maintenance.',
    'ガルフストリーム G200 の導入において、機体選定から詳細な点検・整備に至るまで一貫して対応し、信頼性の高い機体を確保しております。整備完了後は、当社ネットワークを活用し、アメリカにてブラックとゴールドを基調とした特別塗装を実施。品質と意匠性を両立した外観に仕上げております。なお、本機は日本での登録を行わず、米国籍機として運用することで、国内外を問わず柔軟なフライトが可能な体制を確保しております。導入後も、運航および整備の両面から継続的なサポートを提供しております。': 'For the introduction of the Gulfstream G200, we handled everything from aircraft selection to detailed inspection and maintenance, securing a highly reliable aircraft. After completing maintenance, we leveraged our network to commission a special black-and-gold livery in the United States, achieving a finish that balances quality with aesthetic appeal. The aircraft operates as a US-registered aircraft rather than being registered in Japan, enabling flexible flight operations both domestically and internationally. We continue to provide ongoing support covering both operations and maintenance.',
    'エアバス H125 ヘリコプターの売買をトータルでサポートいたしました。売却案件に対し、当社ネットワークを活用し、日本国内において本機の価値をご理解いただけるお客様とのマッチングを実現しております。機体の状態および価値を的確に評価した提案によりご成約へとつなげるとともに、耐空検査をはじめとする各種手続きを当社にて一括対応し、円滑かつ信頼性の高い取引を実現いたしました。導入に至るまでの全工程を社内で完結し、迅速かつ確実な対応を実施。導入後も運用・整備を含めた継続的なサポートを提供しております。': 'We provided total support for the sale and purchase of the Airbus H125 helicopter. For the sale, we leveraged our network to match the aircraft with a suitable buyer in Japan who fully understood its value. Our accurate appraisal of the aircraft\'s condition and worth led to a successful transaction, and we handled all related procedures—including airworthiness inspection—in-house, ensuring a smooth and reliable deal. The entire process through to delivery was completed internally with speed and precision. We continue to provide ongoing support including operations and maintenance.',
    '販売履歴': 'Sales History',

    // ── MAINTENANCE ───────────────────────────────────────────────────────
    '日本最高峰の技術': "Japan's Finest Technology",
    '点検': 'Inspection',
    '整備': 'Maintenance',
    '修理': 'Repair',
    '整備履歴': 'Maintenance History',
    '航空機の安全性と適切な運用を確保するためのプロセスです。点検は、航空機の機体、エンジン、システム、装備などの各部分の状態を評価し、問題や潜在的な故障を発見するために行われます。': 'This is the process of ensuring the safety and proper operation of aircraft. Inspections evaluate the condition of each component—including the airframe, engines, systems, and equipment—to identify problems and potential failures.',
    '航空機整備士や整備スタッフによって行われます。航空機のメンテナンスマニュアルや運航規程に基づき、定められた手順や基準に従って整備を実施します。': 'Carried out by certified aircraft maintenance engineers and technicians. Maintenance is performed in accordance with established procedures and standards set out in the aircraft maintenance manual and operating regulations.',
    '機体、エンジン、システム、装備などの各部分の問題を特定し、必要な修復作業や部品の交換を行います。修理作業は安全性と規制要件に厳密に準拠する必要があります。航空機の履歴と安全性の評価に役立ちます。航空機の適切な状態と安全性を確保するために欠かせないもので航空機の修理は資格を持った専門家によって行われます。': 'Problems in the airframe, engines, systems, and equipment are identified, and the necessary restoration work and parts replacement are carried out. Repair work must strictly comply with safety and regulatory requirements. It helps assess the history and safety of the aircraft, and is essential for maintaining proper condition. All aircraft repairs are performed by qualified specialists.',

    // ── TRANSPORT ─────────────────────────────────────────────────────────
    '輸送サービス': 'Transport Services',
    '故障した機体を現地で修理': 'On-Site Repairs for Grounded Aircraft',
    'エアロラボに持ち帰り修理': 'Return to Aerolab for Repair',
    'フェリーフライト': 'Ferry Flight',
    '航空機の売買と海外フェリーフライトサポート': 'Aircraft Sales & Overseas Ferry Flight Support',
    'フェリーフライト例': 'Ferry Flight Example',
    '現地で機体にトラブルがあってもご安心ください。当社スタッフが現地まで赴き、修理やメンテナンスを行います。万が一、事故や重大な損傷が発生した場合は、機体を適切に評価し、コンテナ輸送による移送や修理にも対応いたします。': 'Rest assured if your aircraft encounters trouble on-site. Our staff will travel to the location to perform repairs and maintenance. In the event of an accident or serious damage, we will properly assess the aircraft and arrange container transport and repair as needed.',
    '現地で修理が難しい場合は、機体をその場で解体し、安全かつ迅速にエアロラボの格納庫へ輸送いたします。当社格納庫にて熟練スタッフが徹底的な修理と整備を行い、機体を最適な状態に復元いたしますのでご安心ください。': 'If repairs are not feasible on-site, we will disassemble the aircraft and transport it safely and swiftly to Aerolab\'s hangar. Our skilled technicians will carry out thorough repairs and maintenance to restore the aircraft to its optimal condition.',
    '他社には真似できない価格とスピードでフライトプランを作成し、海外から日本への輸入を実現いたします。ロシアを含む複雑な空域の通過手続きや各国で必要な許可の取得も、当社の専門スタッフが的確に対応します。また、税関手続きなどの煩雑な業務もすべて代行し、お客様の負担を最小限に抑えることをお約束します。エアロラボなら、最適なルートと安心のサービスで確実にお届けします。': 'We create flight plans at unmatched speed and cost, enabling seamless import of aircraft from overseas to Japan. Our specialists handle complex airspace transit procedures including Russia, and secure all necessary permits from foreign authorities. We also manage all customs-related paperwork to minimize the burden on our clients. With Aerolab, your aircraft will be delivered reliably via the optimal route with complete peace of mind.',
    '航空機を売りたいお客様、または購入したいお客様の機体を海外へフェリーすることも可能です。その際の手続きは、最速かつ最安で行います。': 'We can also ferry aircraft overseas for clients looking to sell or purchase an aircraft. All related procedures are handled in the fastest and most cost-effective manner possible.',

    // ── REMODEL ───────────────────────────────────────────────────────────
    '改造実績': 'Remodeling Work',
    'GARMIN社製G600 Systemへの換装': 'Upgrade to Garmin G600 System',
    '内装の改造(内装の作り変え)': 'Interior Remodeling',
    '特殊用途向けの改造(スカイダイビング用機体のシャッタードア取付)': 'Special Purpose Modification (Skydiving Shutter Door Installation)',
    'アビオニクスとしては電子統合計器への換装、無線機/航空管制用自動応答装置の換装などの実績があります。電子計器に換装するとパイロットの状況判断を助け、安全性/効率性も向上します。これらアビオニクスの換装は航空局からの認可を受けるための証明作業が多く、難しく日本での工事例は少ないです。ですが、当社では長年の経験、技術により認可を取得することができます。': 'We have experience in upgrades such as replacing analog instruments with integrated electronic displays and swapping out radio and transponder systems. Switching to electronic instruments enhances pilot situational awareness and improves both safety and efficiency. These avionics upgrades require extensive certification work for Civil Aviation Bureau approval and are rarely performed in Japan. However, our years of experience and technical expertise allow us to successfully obtain the required approvals.',
    '古くなったBaron 58型の内装の張り替えを実施しました。お客様のイメージに合わせて幅広く対応することができます。もちろん耐火性などの証明も取得し、航空局の認可を得ています。': 'We reupholstered the interior of an aging Baron 58 aircraft. We can accommodate a wide range of design preferences to match each client\'s vision. Naturally, we also obtained the necessary certifications including fire resistance testing, ensuring full Civil Aviation Bureau approval.',
    'スカイダイビングクラブが所有している機体がダイビングを実施する時の利便性増加のためにシャッタードアを装着し当社が設計、製造をし航空局の認可を得ることができます。': 'We designed and manufactured a shutter door for an aircraft owned by a skydiving club to improve convenience during jump operations. We successfully obtained Civil Aviation Bureau approval for the modification.',

    // ── PAINT ─────────────────────────────────────────────────────────────
    '塗装工程': 'Painting Process',
    '塗装結果': 'Paint Results',
    '塗料の乗り良くしたりやスキンのダメージを判定するために洗浄をします。': 'The aircraft is cleaned to improve paint adhesion and to assess any skin damage.',
    '決定したデザインを塗装するためにマスキングをします。': 'Masking is applied to prepare for painting the finalized design.',
    'プライマーを塗り、防錆効果を高め、通常の塗料を塗ります。': 'A primer is applied to enhance corrosion resistance, followed by the topcoat paint.',

    // ── OTHER ─────────────────────────────────────────────────────────────
    '航空機部品': 'Aircraft Parts',
    'パイロット派遣・技術支援・訓練サポート': 'Pilot Dispatch, Technical Support & Training',
    '航空機保険のご案内': 'Aircraft Insurance Guide',
    'ニカドサービス': 'NiCad Battery Service',
    '航空機用機器・アクセサリー販売': 'Aircraft Equipment & Accessories',
    '第三者賠償責任': 'Third-Party Liability',
    '乗客賠償責任': 'Passenger Liability',
    '搭乗者傷害保険': 'Passenger Injury Insurance',

    // Chart labels
    '燃料': 'Fuel',
    '機体整備': 'Airframe Maintenance',
    'エンジン・APU整備': 'Engine/APU Maintenance',
    'その他変動費': 'Other Variable Costs',
    '乗組員給与・福利厚生': 'Crew Salary & Benefits',
    '管理': 'Management',

    // G550 section titles
    '内部': 'Interior',
    '外部': 'Exterior',
    'エンジン・APU': 'Engine & APU',

    // ── Aircraft Specs Main Page ─────────────────────────────────────────
    '航空機検索': 'Aircraft Search',
    'お探しの航空機が決まっていますか？以下に入力して直接ページに移動してください': 'Already know what aircraft you are looking for? Please type it below to go directly to the page',
    '仕様データベース': 'Specifications Database',
    '航空機仕様データベース': 'Aircraft Specifications Database',
    '世界をリードする製造業者の航空機の詳細仕様、性能データ、技術情報をご覧ください': 'Explore detailed specifications, performance data, and technical information for aircraft from leading manufacturers worldwide',
    '航空機を検索...': 'Search aircraft...',
    '航空機タイプ別に閲覧': 'Browse by Aircraft Type',
    '航空機タイプを選択して仕様と性能データをご覧ください': 'Select an aircraft type to explore specifications and performance data',
    'ビジネスジェット': 'Business Jet',
    'エグゼクティブ＆プライベート航空': 'Executive & Private Aviation',
    'ターボプロップ機': 'TurboProp Aircraft',
    '効率的な地域輸送': 'Efficient Regional Transport',
    'ピストン機': 'Piston Aircraft',
    '一般航空': 'General Aviation',
    '回転翼機': 'Rotorcraft',
    'ヘリコプター': 'Helicopters',
    'ジェット旅客機': 'Jet Airliner',
    '商用旅客機': 'Commercial Passenger Jets',
    'ピストン回転翼機': 'Piston Rotorcraft',
    '軽量ヘリコプター': 'Light Helicopters',
    'タービン回転翼機': 'Turbine Rotorcraft',
    '大型＆中型ヘリコプター': 'Heavy & Medium Helicopters',
    '提供内容': "What You'll Find",
    'インタラクティブチャート': 'Interactive Charts',
    'インタラクティブなグラフと比較で性能データを視覚化': 'Visualize performance data with interactive graphs and comparisons',
    '詳細仕様': 'Detailed Specifications',
    '寸法、重量、容量を含む包括的な技術データ': 'Comprehensive technical data including dimensions, weights, and capacities',
    '性能指標': 'Performance Metrics',
    '速度、航続距離、上昇限度、燃料消費データ': 'Speed, range, ceiling, and fuel consumption data',
    '高品質画像': 'High-Quality Images',
    '各航空機の詳細写真と図表': 'Detailed photos and diagrams of each aircraft',
    'データベースについて': 'About This Database',
    '当社の包括的な航空機仕様データベースは、航空愛好家、専門家、研究者向けに正確で最新の情報を提供します。各航空機プロファイルには、詳細な技術仕様、性能データ、インタラクティブな視覚化が含まれており、現代および歴史的な航空機の能力と特性を理解するのに役立ちます。': 'Our comprehensive aircraft specifications database provides accurate, up-to-date information for aviation enthusiasts, professionals, and researchers. Each aircraft profile includes detailed technical specifications, performance data, and interactive visualizations to help you understand the capabilities and characteristics of modern and historical aircraft.',

    // ── Business Jets Page ───────────────────────────────────────────────
    'ビジネスジェットについて': 'About Business Jets',
    'ビジネスジェットは、少人数のグループを快適でスタイリッシュに輸送するために設計された航空機です。地域旅行に最適な軽量ジェットから、大陸間飛行が可能な超長距離機まで様々です。ビジネスジェットは、柔軟性、プライバシー、時間の節約、商用航空会社では利用できない小規模空港へのアクセスを提供します。': 'Business jets are aircraft designed for transporting small groups of people in comfort and style. They range from light jets perfect for regional travel to ultra-long-range aircraft capable of intercontinental flights. Business jets offer flexibility, privacy, time savings, and access to smaller airports unavailable to commercial airlines.',
    '以下の航空機サイズカテゴリーから、ミッション要件に最適なビジネスジェットをお探しください。': 'Browse by aircraft size category below to find the perfect business jet for your mission requirements.',

    // Aircraft categories (JS-generated)
    '軽量ビジネスジェット': 'Light Business Jets',
    '中型ビジネスジェット': 'Midsize Business Jets',
    '大型中距離ビジネスジェット': 'Super Midsize Business Jets',
    '大型ビジネスジェット': 'Large Business Jets',
    '超長距離ビジネスジェット': 'Ultra Long-Range Business Jets',
    '近日公開': 'Coming Soon',
    '詳細': 'Details',
    '航続距離': 'Range',
    '最大速度': 'Max Speed',
    '乗客数': 'Passengers',

    // JS-generated aircraft descriptions
    '主翼上エンジン搭載の軽量ジェット': 'Light jet with over-the-wing engines',
    '燃料容量を増大させたHA-420の改良版': 'Improved HA-420 with more fuel capacity',
    '性能向上版のエリート': 'Enhanced Elite with better performance',
    'システムを強化した最新エリート': 'Latest Elite with upgraded systems',
    '短距離移動向けの超軽量ジェット': 'Very light jet for short hops',
    '経済性の高いエントリーレベルCJ': 'Entry-level CJ with good economy',
    'CJ1より航続距離・速度を向上': 'Improved range and speed over CJ1',
    '立入式キャビン付きの人気軽量ジェット': 'Popular light jet with stand-up cabin',
    'CJファミリー最大モデル': 'Largest of the CJ family',
    '優れた性能の中型ジェット': 'Mid-size jet with strong performance',
    '大陸横断旅行向けの広々キャビン': 'Spacious cabin for transcontinental travel',
    '高速スーパー中型ジェット': 'High-speed super mid-size jet',
    'シタシリーズの長距離フラッグシップ': 'Long-range flagship of the Citation line',
    '経済性の高いエントリーレベルガルフストリーム': 'Entry-level Gulfstream with efficiency',
    'クラシックな大型キャビン軽量ビジネスジェット': 'Classic large-cabin light business jet',
    '現代的な効率と航続距離': 'Modern efficiency and range',
    '快適なキャビンを備えたコーポレートジェット': 'Corporate jet with comfortable cabin',
    'G300ベースの長距離版': 'Derived from G300 with longer range',
    '高性能スーパー中型ジェット': 'Highly capable super mid-size jet',
    'バランスの取れた長距離機': 'Well-balanced long-range performer',
    '高度なコックピットを備えた次世代機': 'Next generation with advanced cockpit',
    '卓越した性能とキャビン快適性を誇る超長距離ジェット': 'Ultra-long-range jet with exceptional performance and cabin comfort',
    '高速・長距離フラッグシップ': 'High-speed, long-range flagship',
    'フラッグシップ超長距離機': 'Flagship ultra-long-range aircraft',
    '記録的な能力を持つ航続距離延長版': 'Extended range version with record capability',

    // Category description (JS-generated)
    'HondaJet機（航続距離順）': 'HondaJet aircraft ordered by range.',
    'Cessna機（航続距離順）': 'Cessna aircraft ordered by range.',
    'Gulfstream機（航続距離順）': 'Gulfstream aircraft ordered by range.',

    // ── G550 Aircraft Page ───────────────────────────────────────────────
    'ガルフストリーム G550': 'Gulfstream G550',
    '超長距離ビジネスジェット': 'Ultra Long-Range Business Jet',
    'ガルフストリームG550超長距離ビジネスジェットの詳細仕様、性能分析、コスト内訳、インタラクティブ航続距離マップです。': 'Detailed specifications, performance analysis, cost breakdown, and interactive range mapping for the Gulfstream G550 ultra long-range business jet.',

    // Summary
    '概要': 'Summary',
    'フェリー航続距離': 'Ferry Range',
    '通常巡航速度': 'Normal Cruise Speed',
    '最大乗客数': 'Maximum Passengers',
    'ガルフストリーム G550は2003年から2021年まで製造され、2名の乗組員を必要とし、最大18名の乗客を輸送できます。最大運用高度は15,545 M（51,000 FT）、通常巡航速度は904 KMH（488 KTS）、最大航続距離は12,501 KM（6,750 NM）です。': 'The Gulfstream G550, manufactured from 2003-2021, requires a 2 person crew and can transport up to 18 passengers. The aircraft has a maximum operating altitude of 15,545 M (51,000 FT), a normal cruise speed of 904 KMH (488 KTS), and a 12,501 KM (6,750 NM) maximum range.',

    // Cost
    'コスト分析': 'Cost Analysis',
    '年間飛行時間：': 'Annual Flight Hours:',
    '計画された年間飛行時間を入力してカスタマイズされたコスト予測を確認してください。': 'Enter your planned annual flight hours to see customized cost projections.',
    '通貨：': 'Currency:',
    '為替レートはライブプロバイダーから更新されます。': 'Currency rates update from a live exchange-rate provider.',
    'ライブ燃料価格': 'Live Fuel Price',
    '最新レートを取得中…': 'Fetching latest rate…',
    'レート：': 'Rate:',
    '最終更新：': 'Last updated:',
    'レート更新': 'Refresh Rate',
    '年間総コスト概要': 'Total Annual Cost Summary',
    '年間変動費': 'Annual Variable Cost',
    '年間固定費': 'Annual Fixed Cost',
    '年間総予算': 'Total Annual Budget',
    '月間総予算': 'Total Monthly Budget',
    '時間あたりコスト': 'Cost Per Hour',
    '時間変動費': 'Hourly Variable Cost',
    '燃料': 'Fuel',
    '機体メンテナンス': 'Airframe Maintenance',
    'エンジン/APUメンテナンス': 'Engine & APU Maintenance',
    '変動費その他': 'Miscellaneous Variable',
    '時間変動費合計': 'Total Hourly Variable Costs',
    '年間固定費明細': 'Annual Fixed Cost',
    '乗組員給与＆福利厚生': 'Crew Salary & Benefits',
    '乗組員訓練': 'Crew Training',
    '格納庫': 'Hangar',
    '保険': 'Insurance',
    'その他固定費': 'Miscellaneous Fixed',
    '年間固定費合計': 'Total Annual Fixed Costs',
    '変動費内訳': 'Variable Cost Breakdown',
    '固定費内訳': 'Fixed Cost Breakdown',

    // Performance
    '性能': 'Performance',
    '速度性能': 'Speed Performance',
    '最大速度': 'Maximum Speed',
    '長距離巡航': 'Long-Range Cruise',
    '航続距離能力': 'Range Capabilities',
    '最大航続距離': 'Maximum Range',
    '上昇限度': 'Service Ceiling',
    '上昇率': 'Rate of Climb',
    '重量仕様': 'Weight Specifications',
    '最大離陸重量': 'Max Takeoff Weight',
    '最大着陸重量': 'Max Landing Weight',
    '基本運用重量': 'Basic Operating Weight',
    '燃料消費': 'Fuel Consumption',
    '時間あたり燃料使用量': 'Fuel Usage Per Hour',
    '総燃料容量': 'Total Fuel Capacity',
    '燃料重量': 'Fuel Weight',
    '滑走路距離要件': 'Runway Distance Requirements',
    'メートル': 'Meters',
    'フィート': 'Feet',
    '最短離陸距離': 'Minimum Takeoff Distance',
    '最短着陸距離（PART 91）': 'Minimum Landing Distance (PART 91)',
    '最短着陸距離（PART 135）': 'Minimum Landing Distance (PART 135)',
    '滑走路の測定値は、晴天・乾燥した滑走路を基準とした最短値です。距離は乗客の体重、手荷物の重量、風、滑走路の状態、気温、空港の標高によって変わる場合があります。': 'The runway measurements are the minimum values based on a clear day and dry runway. The distance may change depending on passenger weights, baggage weight, winds, runway conditions, temperature and airport elevation.',
    'インタラクティブ航続距離マップ': 'Interactive Range Map',
    '出発空港を検索：': 'Search Departure Airport:',
    '空港名またはコードで検索（例：東京またはHND）...': 'Search by airport name or code (e.g., Tokyo or HND)...',
    '空港を検索して選択し、その場所からのG550の航続距離を確認': "Search and select an airport to see the G550's range from that location",
    '青いレンジリングは、ガルフストリーム社公表の航続距離です。これは乗客8名＋乗員4名、かつ良好な風・気象条件を前提としています。乗客が増えると最大ペイロードを超えるため、追加搭乗には燃料を減らす必要があります。': 'The blue range ring represents the range published by Gulfstream. This assumes 8 passengers and 4 crew under favorable wind and weather conditions. As passenger count increases beyond the maximum payload, fuel must be reduced to accommodate additional occupants.',
    '最大の19名搭乗時には、重量に対応するため大幅な燃料削減が必要です。赤いレンジリングはその際の平均的な目安ですが、実際の航続距離は天候や風の影響で増減します。': 'At full capacity of 19 passengers, a significant fuel reduction is required to manage the weight. The red range ring provides an average estimate for this configuration; actual range will vary with weather and wind conditions.',
    'フェリー飛行航続距離：6,776 NM（12,548 KM）': 'Ferry Flight Range: 6,776 NM (12,548 KM)',
    '満席時航続距離（18名）：4,200 NM（7,778 KM）': 'Full Seat Range (18 Passengers): 4,200 NM (7,778 KM)',

    // Design
    '設計': 'Design',
    '座席配置': 'Seating Configuration',
    '標準構成': 'Typical Configuration',
    '最小乗組員': 'Minimum Crew',
    '客室乗務員': 'Flight Attendants',
    'キャビン寸法': 'Cabin Dimensions',
    'キャビン容積': 'Cabin Volume',
    'キャビン高さ': 'Cabin Height',
    'キャビン幅': 'Cabin Width',
    'キャビン長さ': 'Cabin Length',
    '荷物＆収納': 'Baggage & Storage',
    '総荷物容量': 'Total Baggage Capacity',
    '内部荷物': 'Internal Baggage',
    '外部荷物': 'External Baggage',
    '外装寸法': 'Exterior Dimensions',
    '全長': 'Overall Length',
    '翼幅': 'Wingspan',
    '高さ': 'Height',
    '翼面積': 'Wing Area',
    'パワープラント': 'Powerplant',
    'エンジン': 'Engines',
    'エンジンモデル': 'Engine Model',
    'エンジンあたり推力': 'Thrust Per Engine',
    '総推力': 'Total Thrust',
    'モデル': 'Model',
    '出力': 'Power Output',

    // ── Runway chart X-axis ────────────────────────────────────────────────────
    '距離': 'Distance',

    // ── G550 Cost Section ──────────────────────────────────────────────────
    '計算設定': 'Calculation Settings',
    '単位系': 'Unit System',
    'メートル法': 'Metric',
    'ヤード・ポンド法': 'Imperial',

    // ── G550 Disclaimer ─────────────────────────────────────────────────────
    '免責事項': 'Disclaimer',
    '本ページに掲載されている航空機の仕様および性能データ等の情報は、一般的な参考情報として提供されています。これらのデータは、メーカーの公開資料、業界情報、および当社独自の推定に基づいて作成されており、一部には概算値や前提条件が含まれる場合があります。': 'The aircraft specifications, performance data, and related information presented on this page are provided for general informational purposes only. Data is compiled from publicly available manufacturer publications, industry sources, and internal estimates, and may include approximations or assumptions.',
    '航続距離、搭載量、速度などの性能数値は、機体の仕様や状態、気象条件、運用環境などのさまざまな要因によって変動するため、実際の数値は掲載内容と異なる場合があります。': 'Performance figures such as range, payload, and speed are influenced by variables including aircraft configuration, condition, weather, and operational factors. Actual results may vary from the values shown.',
    '本ページに掲載されている画像およびビジュアルは、AI生成または当社により作成されたイメージであり、特定の実機を正確に再現したものではありません。': 'All images and visual representations are AI-generated or created in-house for illustrative purposes only and do not depict any specific aircraft or guarantee accuracy in design or configuration.',
    'また、メーカーの更新、規制の変更、市場動向、地政学的要因などにより、掲載情報が最新でない場合があります。当社は、本情報の正確性、完全性、最新性についていかなる保証も行いません。': 'Information may become outdated due to manufacturer updates, regulatory changes, market conditions, or geopolitical factors. We do not guarantee the accuracy, completeness, or timeliness of the content provided.',
    '本情報は「現状有姿」で提供されるものであり、その利用によって生じたいかなる損害についても、当社は一切の責任を負いません。': 'All information is provided "as is" without warranties of any kind, and we assume no liability for errors, omissions, or outcomes resulting from its use.',
};

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = englishTranslations;
}
